DEFAULT_CONFIG = {
    "download": {
        "workers": 4,
        "per_provider_workers": 3,
        "retries": 5,
        "connect_timeout": 20,
        "read_timeout": 120,
        "resume": True,
        "overwrite": False,
    },
    "archive": {
        "root": "./data",
        "layout": "year_doy",
        "auto_extract": False,
        "keep_compressed": False,
    },
    "provider": {
        "priority": [
            "whu",
            "kasi",
            "esa",
            "ign",
            "sopac",
            "bdsmart",
            "bkgftp",
            "bkg",
            "noaa",
        ],
    },
    "products": {
        "default_tier": "auto",
        "default_system": "auto",
        "center_priority": ["IGS", "COD", "GFZ", "ESA", "GRG", "WUM"],
        "multi_gnss_center_priority": ["IGS", "WUM", "GFZ", "COD", "ESA"],
        "provider_priority": ["esa", "ign", "whu", "bkgftp", "bkg", "igsfiles"],
        "prefer_same_center": True,
        "prefer_same_tier": True,
        "allow_mixed_center": True,
        "availability_cache": True,
    },
    "network": {
        "proxy": None,
        "mode": "system",
        "host": "",
        "port": 0,
        "username": "",
        "password": "",
        "use_for_http": True,
        "use_for_sftp": True,
        "use_for_ftp": True,
        "chromedriver_path": "",
    },
    "stations": {
        "catalog_path": None,
        "auto_seed": False,
    },
    "logging": {
        "level": "INFO",
    },
    "appearance": {
        "theme": "system",
        "language": "en",
    },
}
